# Generated by Django 3.2.7 on 2022-04-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_noeud_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='noeud',
            name='question',
            field=models.CharField(default='', max_length=100),
        ),
    ]
