# Generated by Django 3.1.5 on 2022-04-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20220414_1943'),
        ('administration', '0004_noeud_question'),
    ]

    operations = [
    ]
