# Generated by Django 3.1.5 on 2022-05-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/user/ens/'),
        ),
    ]
