# Generated by Django 3.1.5 on 2022-04-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignant', '0003_alter_valcaracteristique_information'),
        ('enseignant', '0002_auto_20220414_1943'),
    ]

    operations = [
    ]
